name: Destrucción de infraestructura 'Integramos Herramientas'

on:
  workflow_dispatch: 

jobs:
  destruir:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      #! Clonamos el repositorio en la máquina ubuntu
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      #! Nos aseguramos de que terraform esté instalado
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      #! Nos movemos al directorio donde está el terraform
      - name: Iniciar Terraform
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform init
          ls

      #! Hacemos un plan para ver lo que va a destruir
      - name: Terraform Plan para destruir
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform plan -destroy -out=tfplan_destroy

      #! Terraform destroy para destruir la IaC
      - name: Destroy Terraform Infrastructure
        id: destroy_terraform
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform apply -destroy -auto-approve tfplan_destroy
