name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  despliegue:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      #! Clonamos el repositorio en la máquina ubuntu
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      #! Nos movemos al directorio donde está el terraform
      #! e iniciamos la configuración
      - name: Iniciar Terraform
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform init

      #! Hacemos terraform destroy
      - name: Terraform destroy
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform destroy --auto-approve
