name: Despliegue continuo de 'Integramos Herramientas'

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      #! Clonamos el repositorio en la máquina ubuntu
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      #! Nos aseguramos de que terraform esté instalado 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      #! AWS Cli
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      #! Hago el comando para crear el script que va a leer la creación del S3
      - name: Comando SH para script
        run: |
           pwd
           cd ./Paris-IA/Terraform
           sh upload.sh ../Website files_list.json

      #! Nos movemos al directorio donde está el terraform
      #! e iniciamos la configuración
      - name: Iniciar Terraform 
        run: |
          pwd
          cd ./Paris-IA/Terraform
          ls
          terraform init

      #! Hacemos un plan para saber lo que va a crear
      - name: Terraform Plan
        run: |
          pwd
          cd ./Paris-IA/Terraform
          terraform plan -out=tfplan

      #! Terraform apply para que aplique la IaC (Infra como Code)
      - name: Apply Terraform
        id: apply_terraform
        #? Aquí le indico el archivo que creé con el terraform plan.
        #? Me ahorro el --auto-approve
        run: |
          pwd
          cd ./Paris-IA/Terraform
          terraform apply tfplan

      #! Verificamos los outputs
      - name: Verificar outputs
        run: |
          cd ./Paris-IA/Terraform
          terraform output