name: Despliegue continuo de 'Integramos Herramientas'

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      #! Clonamos el repositorio en la máquina ubuntu
      - name: Checkout repository
        uses: actions/checkout@v4.2.2


      #! Nos aseguramos de que terraform esté instalado
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: latest

      #! Nos movemos al directorio donde está el terraform
      #! e iniciamos la configuración
      - name: Iniciar Terraform
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform init

      #! Hacemos un plan para saber lo que va a crear
      - name: Terraform Plan
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform plan -out=tfplan

      #! Terraform apply para que aplique la IaC (Infra como Code)
      - name: Apply Terraform
        id: apply_terraform
        #? Aquí le indico el archivo que creé con el terraform plan.
        #? Me ahorro el --auto-approve
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          terraform apply tfplan

      #! Verificamos los outputs
      - name: Verificar outputs
        run: |
          cd ./Integramos-herramientas  
          cd ./Terraform
          terraform output

      #! Aprovecho mis outputs para obtener la IP Pública
      - name: Obtener la IP pública de la instancia
        id: get_instance
        run: |
          pwd
          cd ./Integramos-herramientas
          cd ./Terraform
          pwd
          instance_public_ip=$(terraform output -raw instance_public_ip)
          echo "public_ip=$instance_public_ip" >> $GITHUB_ENV
